import { ProgramEditor } from '../../app/ProgramEditor'
import { useCode } from '../../store/code-store'
import { useTransport } from '../../store/transport-store'
import { uiStore, useUi } from '../../store/ui-store'

/** Generated code under the tracks: "Synced" mirrors the UI, "Direct edit" edits it (SPEC 6.1, 6.6). */
export function CodePanel() {
  const mode = useUi((s) => s.codeMode)
  const hasDraft = useCode((s) => s.draft !== null)
  const globalError = useTransport((s) => s.globalError)
  const direct = mode === 'direct'

  return (
    <section
      aria-labelledby="code-title"
      className="flex min-h-0 min-w-0 flex-col overflow-hidden border-t border-line bg-bg-code"
    >
      <header className="flex items-center gap-3 border-b border-line px-5 py-2.5">
        <h2 id="code-title" className="text-track-name font-medium">
          Strudel code
        </h2>
        <span className="text-body text-text-2">
          {direct
            ? 'Ctrl+Enter to evaluate, changes flow back into the interface'
            : 'Generated by the interface, editable by hand'}
        </span>
        <div className="ml-auto flex items-center gap-4">
          <div role="group" aria-label="Code mode" className="flex rounded-control bg-raised p-0.5 text-body">
            {(['synced', 'direct'] as const).map((m) => (
              <button
                key={m}
                type="button"
                aria-pressed={mode === m}
                onClick={() => uiStore.getState().setCodeMode(m)}
                className={`rounded-xs px-3 py-1 ${mode === m ? 'bg-active text-accent' : 'text-text-2 hover:text-text'}`}
              >
                {m === 'synced' ? 'Synced' : 'Direct edit'}
                {m === 'direct' && hasDraft && <span className="text-accent"> *</span>}
              </button>
            ))}
          </div>
          <button
            type="button"
            onClick={() => uiStore.getState().setScreen('code')}
            className="text-body text-accent hover:text-accent-hover"
          >
            Full screen →
          </button>
        </div>
      </header>
      {globalError && (
        <p role="alert" className="px-5 pt-2 text-small text-danger">
          {globalError}. The previous version keeps playing.
        </p>
      )}
      <ProgramEditor editable={direct} label={direct ? 'Strudel code, editable' : 'Generated Strudel code'} />
    </section>
  )
}
