import { useEffect, useRef } from 'react'
import { CodeView } from '../../components/code-view'
import { useCode } from '../../store/code-store'
import { useTransport } from '../../store/transport-store'
import { uiStore, useUi } from '../../store/ui-store'

/** Generated code, read-only in "Synced" mode, with the selected track's lines highlighted. */
export function CodePanel() {
  const hostRef = useRef<HTMLDivElement>(null)
  const viewRef = useRef<CodeView | null>(null)
  const generated = useCode((s) => s.generated)
  const selectedTrackId = useUi((s) => s.selectedTrackId)
  const errors = useTransport((s) => s.errors)
  const globalError = useTransport((s) => s.globalError)

  useEffect(() => {
    if (!hostRef.current) return
    const view = new CodeView(hostRef.current, 'Generated Strudel code')
    viewRef.current = view
    return () => {
      view.destroy()
      viewRef.current = null
    }
  }, [])

  useEffect(() => {
    const view = viewRef.current
    if (!view || !generated) return
    view.setCode(generated.code.replace(/\n$/, ''))
    const errorLines: number[] = []
    for (const [trackId, error] of Object.entries(errors)) {
      const range = generated.lineMap[trackId]
      if (error.line !== undefined) errorLines.push(error.line)
      else if (range) for (let line = range.from; line <= range.to; line++) errorLines.push(line)
    }
    view.highlight(selectedTrackId ? (generated.lineMap[selectedTrackId] ?? null) : null, errorLines)
  }, [generated, selectedTrackId, errors])

  return (
    <section aria-labelledby="code-title" className="flex min-h-0 flex-col border-t border-line bg-bg-code">
      <header className="flex items-center gap-3 border-b border-line px-5 py-2.5">
        <h2 id="code-title" className="text-track-name font-medium">
          Strudel code
        </h2>
        <span className="text-body text-text-2">Generated by the interface, editable by hand</span>
        <div className="ml-auto flex items-center gap-4">
          <div role="group" aria-label="Code mode" className="flex rounded-control bg-raised p-0.5 text-body">
            <button type="button" aria-pressed="true" className="rounded-xs bg-active px-3 py-1 text-accent">
              Synced
            </button>
            <button
              type="button"
              aria-pressed="false"
              disabled
              title="Direct editing arrives with the code editor"
              className="px-3 py-1 text-text-2 disabled:opacity-60"
            >
              Direct edit
            </button>
          </div>
          <button
            type="button"
            onClick={() => uiStore.getState().setScreen('code')}
            className="text-body text-accent hover:text-accent-hover"
          >
            Full screen →
          </button>
        </div>
      </header>
      {globalError && (
        <p role="alert" className="px-5 pt-2 text-small text-danger">
          {globalError}. The previous version keeps playing.
        </p>
      )}
      <div ref={hostRef} className="min-h-0 flex-1 overflow-hidden" />
    </section>
  )
}
