// Writes THIRD_PARTY_LICENSES from the installed production dependencies, plus the Geist font license.
// Usage: bun run licenses          (write the file)
//        bun run licenses --check  (fail if a dependency license is not AGPL-compatible, write nothing)
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { collectProductionPackages, isCompatible } from './licenses'

const root = join(import.meta.dirname, '..')
const packages = collectProductionPackages(root)
const incompatible = packages.filter((p) => !isCompatible(p.license))

if (process.argv.includes('--check')) {
  for (const p of packages)
    console.log(`${isCompatible(p.license) ? 'ok  ' : 'FAIL'} ${p.name}@${p.version} ${p.license}`)
  if (incompatible.length > 0) {
    console.error(`\n${incompatible.length} package(s) with a license not known to be AGPL-3.0 compatible.`)
    process.exit(1)
  }
  console.log(`\n${packages.length} packages, all AGPL-3.0 compatible.`)
  process.exit(0)
}

const rule = '='.repeat(80)
const sections = packages.map((p) =>
  [
    rule,
    `${p.name} ${p.version}`,
    `License: ${p.license}`,
    ...(p.repository ? [`Repository: ${p.repository}`] : []),
    '',
    p.licenseText ?? `No license file is shipped with this package. Its declared license is ${p.license}.`,
  ].join('\n'),
)

const geist = [
  rule,
  'Geist and Geist Mono fonts',
  'License: OFL-1.1',
  'Repository: https://github.com/vercel/geist-font',
  '',
  readFileSync(join(root, 'resources', 'fonts', 'OFL.txt'), 'utf8').trim(),
].join('\n')

const header = [
  'Third-party licenses for Motif',
  '',
  'Motif is licensed under AGPL-3.0-or-later (see LICENSE). It includes the software and fonts listed',
  'below, each under its own license. Bundled samples are listed in resources/samples/LICENSES.md.',
  '',
  'This file is generated by scripts/third-party-licenses.ts. Do not edit it by hand.',
].join('\n')

writeFileSync(join(root, 'THIRD_PARTY_LICENSES'), `${[header, ...sections, geist].join('\n\n')}\n`)
console.log(`Wrote THIRD_PARTY_LICENSES: ${packages.length} packages and the Geist fonts.`)
if (incompatible.length > 0) {
  console.warn(`Warning: ${incompatible.map((p) => `${p.name} (${p.license})`).join(', ')} need review.`)
}
